name: Publish to npm

on:
  push:
    branches:
      - main # or the branch you want to use for publishing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 1git remote add origin https://github.com/DawidWraga/use-url.git4 # or the version you want to use

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build # or the build script you have in your package.json

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
