name: Publish to npm

on:
  push:
    branches:
      - main # or the branch you want to use for publishing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Print pnpm-lock.yaml content
        run: cat pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm run build # or the build script you have in your package.json

      - name: Show Git status and differences
        run: |
          git status
          git diff

      - name: Publish to npm
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
