name: Publish to npm

on:
  push:
    branches:
      - main # or the branch you want to use for publishing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17 # or the version you want to use

      - name: Install pnpm
        run: curl -L https://unpkg.com/@pnpm/self-installer | node

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm run build # or the build script you have in your package.json

      - name: Publish to npm
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
